'use strict';
// Fights chosen on purpose: which target a hunt takes on, and the Ender
// Dragon fight's next action.
const { define } = require('./index');
const { endDecisionInstructions } = require('./end-state');

define({
  id: 'hunt_target', area: 'combat', parent: 'rung_progress', kind: 'combat', primitive: 'choice', stakes: 'high', tree: true,
  question: 'The request needs a mob\'s drop: which observed mob should the bot fight now, or leave them for now?',
  trigger: 'A mob hunt step with at least one candidate in view that is reachable and isolated, or on a blaze hunt a blaze within twenty-four, in sight or heard through the walls, and a stand to take them from, the bot on ground it can fight from (dry, not on a one-wide span, air to breathe). A blaze whose every way in the open ends within a fireball\'s push of lava or a deep drop is not offered to fight in the open (notFoughtInTheOpen in the state).',
  source: 'src/mob-hunt.js (huntObserved, fitness, fitnessSays)',
  options: [
    { pattern: 'hunt_\\d+', label: 'fight this mob', when: 'observed, reachable, isolated from others of its kind; said in a sentence with where it is and whether it is in sight or only heard, how it is fought with what is carried, what it drops and that the resource is what the request needs, the fight\'s estimate (with the others that reach the bot there fighting too, a shooter in sight within its reach or anything else within sixteen, and the one alone beside it; a blaze spawner near said) and the bot\'s fitness: health against the fourteen the code once required, hunger and whether health comes back, food carried, fire, and the kit', level: 'root', dynamic: true },
    { key: 'dig_in_and_fight', label: 'dig a hole into the brick or netherrack and take the blazes from inside it', when: 'a blaze hunt with a blaze within twenty-four (in sight or heard), a sword or axe carried, and rock for the hole beside the bot or a wall within five blocks; said as the encounter stance of that name, with the push where the bot stands; held until a rod is in hand, the blazes are quiet twenty seconds or two minutes pass, then the rods picked up', level: 'root' },
    { key: 'fight_at_spawner', label: 'take the blazes at their spawner\'s cage, under a ceiling', when: 'a blaze hunt with a blaze within twenty-four (in sight or heard), a spawner within twenty-four and a cell within three of it under a ceiling, no drop or lava within a push, within twenty-four blocks of walking; held as the hole is', level: 'root' },
    { key: 'back_to_wall', label: 'take the blazes from footing with a wall at its back', when: 'a blaze hunt with a blaze within twenty-four (in sight or heard) and such footing within eight blocks of walking; held as the hole is', level: 'root' },
    { key: 'dig_in_at_spawner', label: 'dig a hole into the rock beside the blaze spawner\'s cage, the mouth toward it, and take its blazes at the mouth', when: 'a blaze hunt with a blaze within twenty-four, a sword or axe carried, digging at hand, and a blaze spawner within twenty-four with rock for such a hole within four and a half blocks of its cage and thirty of walking; said with the walk, the rock, the digging, what the spawner makes and where, that every shot comes in through the mouth, and what the arena measured of it (blaze-stand.js MEASURED); held as the hole is, the rods at the mouth picked up between volleys', level: 'root' },
    { key: 'break_spawner', label: 'walk to the blaze spawner behind the shield, break it with the pickaxe, then go at the blazes left with the sword', when: 'a blaze hunt with a blaze within twenty-four, a sword or axe carried, a shield in the off hand, a pickaxe, and a blaze spawner within twenty-four with a cell within block reach of its cage and thirty of walking; where rods are still owed, said first, before anything else: how many are owed and that breaking ends every one this spawner would ever give, for good, with the nearest other known spawner\'s distance or that none is known; then the walk, the digging, and what the arena measured of it; the blazes left then fought as close_in (note 740)', level: 'root' },
    { key: 'close_in', label: 'go at the blazes with the sword, striking each in reach; with a shield, up and facing each volley as it comes and down between, without one straight in', when: 'a blaze hunt with a blaze within twenty-four, a sword or axe carried, and a blaze over ground the bot can stand on within a sword\'s reach of it; said with the nearest one\'s distance, how many are over ground and over lava, the volley\'s glow and rest, what the shield takes and what it leaves, what the arena measured of it with the same kit (blaze-stand.js MEASURED), and its price worked from the fight at hand (closeInCost: how many blazes see the bot and over how wide an arc, how many the shield faced at their middle covers, the lulls between volleys the walk needs, the swings each takes with the shield down while the rest shoot, the burning, a live spawner\'s newcomers, and when the health runs out if it does); run for forty-five seconds, until a rod is carried or until six health is gone, then asked again, or ended sooner, said why, when a volley\'s cycle passes without a step nearer a blaze or a swing; the rods picked up between volleys; offered with or without a shield (note 614), said so, and priced with every fireball landing at its chance where none is carried; every option at a blaze fight says what it gains toward the rods the goal still needs (kills by its own figures, a kill only if one comes to the sword, or none)', level: 'root' },
    { key: 'charge_nearest', label: 'charge the nearest blaze alone with the sword, kill it, pick up its rod, and be asked again', when: 'a blaze hunt with a blaze within twenty-four, a sword or axe carried, more than one blaze about, and the nearest over ground the bot can stand on within a sword\'s reach of it; priced as close_in is, up to that one kill (closeInCost upTo), with the others that see the bot shooting meanwhile, with or without a shield (note 614)', level: 'root' },
    { key: 'box_at_spawner', label: 'wall the bot in with blocks two to four and a half from the blaze spawner\'s cage, one block open at head height toward it, and take its blazes through the window', when: 'only where the arena measures it (BLAZE_TACTICS_ALL=1), not in play: at the drill\'s live spawner with four blazes about it lost 3 runs of 5 and took no rod (note 606); there, a blaze hunt with a blaze within twenty-four, a sword or axe carried, a blaze spawner within sixteen, a cell within sixteen blocks of walking with ground under each side, no lava beside it and no more blocks to place than are carried; said with the walk, the blocks, that only a blaze in line with the window sees in and every shot comes from in front where the shield faces, that a blaze more than two off hovers and shoots and one within two that sees in comes at the window into the sword, the blazes within four of the cell now, the rods fetched through the block under the window, what the building costs in their fire, and what the arena measured of it (blaze-stand.js MEASURED); held up to forty-five seconds, until a rod is carried, six health is gone or twenty seconds with no blaze in line or within eight', level: 'root' },
    { key: 'box_here', label: 'wall the bot in with blocks where it stands, one block open at head height toward the spawner or the blazes, and hold it', when: 'a blaze hunt with a blaze within twenty-four, a sword or axe carried, a cell within two steps with ground under each side, no lava beside it and no more blocks to place than are carried; said and held as box_at_spawner is, with whether the spawner puts its blazes beside it (only within four of its cage) and that food can be eaten in it', level: 'root' },
    { key: 'light_spawner', label: 'put torches on and round the blaze spawner\'s cage until every open cell it spawns in is at light twelve or more, the shield up for each volley', when: 'only where the arena measures it (BLAZE_TACTICS_ALL=1), not in play: at the drill\'s live spawner with four blazes about it lost 4 runs of 5 and took no rod (note 606); there, a blaze hunt with a blaze within twenty-four, a sword or axe carried, a blaze spawner within sixteen with cells still dark, torch spots from which every one of them can be lit, and torches carried or coal and sticks to make them (four a pair); said with the torches, the game\'s rule (a blaze spawner\'s tries fail at light 12 or more, and a round in which every try fails is tried again the next tick, so every open cell within four of the cage, one below to one above, has to be lit), that the spawner makes them again once the torches are taken down, the blazes about left to fight after, the seconds and damage in their fire, and what the arena measured of it', level: 'root' },
    { key: 'corner_ambush', label: 'stand round a corner where no blaze has a line to the bot, facing the corner, and strike what comes round it', when: 'a blaze hunt with a blaze within twenty-four, a sword or axe carried, a cell within ten blocks of walking that none of the blazes about sees, with a cell beside it one of them does and no drop or lava within a push; said with what a blaze does out of sight (flies toward the bot a quarter second, gives it up after three seconds unseen, then wanders), the walk in their fire and what the arena measured of it; held thirty seconds, until a rod is carried or six health is gone', level: 'root' },
    { key: 'leave_and_heal', label: 'go out of every blaze\'s sight, eat, and wait until the health is full where it can come back, then be asked again', when: 'a blaze hunt with a blaze within twenty-four, a sword or axe carried, health under twenty, and a cell within fourteen blocks of walking none of the blazes about sees, at least four from the nearest; said with the walk in their fire, the healing\'s pace (a point each half second at hunger twenty with saturation, each four seconds at eighteen or nineteen) and seconds to full (said as never where hunger is under eighteen with too little carried to bring it to eighteen: then no health comes back, and the option is only out of the fire and the volleys), that the blazes stay and a spawner within sixteen makes more meanwhile, and what the arena measured of it; run until the health is full or sixty seconds, or, where none can come back, until out of sight with the fire on the body out', level: 'root' },
    { key: 'defer', label: 'leave them for now', when: 'always; said with the fitness, the shooters that still reach the bot where it stands (leaving is not out of their fire), and what the hunt does meanwhile when the bot is short of it (food, cover, health); on a blaze hunt, that it gains nothing toward the rods still needed, the blazes staying, and that those left are not offered again for two minutes (note 614)', level: 'root' },
  ],
  instructions: {
    task: 'The resource the request needs drops from these mobs. Choose which observed mob to fight now, or leave them for now if the situation is unsuitable.',
    guidance: 'Every target listed is reachable, with no crowd of other kinds beside it; where other mobs reach the bot, its fight is priced with them. fitness is the bot\'s state for a fight: the code once refused one under fourteen health or hunger, without a full kit, or with hunger under eighteen and nothing to eat (health comes back only at eighteen or more); those are facts here, not rules. A bot alight in the Nether has no water to put the fire out: a cauldron of water or a fire resistance potion does, where one is carried or near, and otherwise only waiting burns it off. Health, food and the resource still needed are in the state; on a blaze hunt, blazes says how many are about, seen or heard, at what heights, a spawner seen, and that blaze rods come from nothing else. A stand (a hole, the spawner\'s cage, a wall at the back) is priced as the fight in the open is: the price of each, set against leaving them, is the choice. On a blaze hunt playedRecord is what the bot\'s own fights with blazes came to in the trials, by the health and hunger a fight began at and by how many blazes were about (three within sixteen blocks is a spawner\'s): the row the bot is in is what a fight begun now has been. playedAnswers, and the sentence ending a stand that has one, say what came after each kind of answer (a strike, cover, a retreat, going away to heal) in the fights of the trials given in a situation like this one, with the fights counted, the rods taken after it and the deaths after it, only where at least five fights are in the row; what happened after such answers, not what the answer caused. Near a live spawner the fight in the open is also priced with the blazes it puts in over the fight\'s own seconds. For a blaze target, blazeCounts (note 665) says the blazes in sight now, the spawner\'s rule (up to four every ten to forty seconds while the bot is within sixteen, until six are about, none beyond sixteen) and what fights at a live spawner came to by how many blazes were about, with the number of fights in each row: counts of fights the bot played in states the rows do not hold alike, not what entering with that many would do.',
  },
  ungated: 'every target offered is reachable and isolated and the bot has footing for a fight; the fitness is said in full on every option, a close call between fighting and leaving it is a preference',
});

// The kit for a fight, offered and not required (src/mob-hunt.js
// kitChoice): the planner once required it, and a Nether blaze hunt with a
// stone sword planned iron ore it could not dig there, 1,130 times in
// twenty-five minutes (mid-227-r-nether-1, note 476).
define({
  id: 'combat_kit', area: 'combat', parent: 'rung_progress', kind: 'combat', primitive: 'choice', stakes: 'medium', tree: true,
  question: 'Pieces of the combat kit (iron-or-better sword, helmet, chestplate, leggings, boots, a shield) are missing: go on with what is carried, make them here first, or go back to the Overworld for them?',
  trigger: 'Before a hunt of a mob that fights back, or the crossing into the Nether or the End, with a piece of the kit neither carried nor set aside, and more than one way on; held ten minutes while the same options stand.',
  source: 'src/mob-hunt.js (prepareCombatGear, kitChoice, kitPieces)',
  options: [
    { key: 'fight_with_carried', label: 'go on with what is carried', when: 'always; said with the weapon and armour carried and one fight\'s estimate against the mob hunted', level: 'root' },
    { key: 'make_kit_here', label: 'make the pieces that can be made here first', when: 'a missing piece can be made from sources in this dimension; said with the iron it takes and the steps', level: 'root' },
    { key: 'return_for_kit', label: 'go back to the Overworld for the pieces', when: 'outside the Overworld, a missing piece made only from Overworld ore; said with the iron, the ore and the trip to the portal', level: 'root' },
  ],
  instructions: {
    task: 'A fight needs a kit the bot is short of. Choose to go on with what is carried, to make the missing pieces here, or to go back to the Overworld for them.',
    guidance: 'Each option says what it costs: the fight as it would go with what is worn and held, the iron and steps to make a piece, the walk to the portal. Fighting without armour is a real choice, not a rule broken; iron ore is found only in the Overworld.',
  },
});

define({
  id: 'dragon_fight', area: 'endgame', parent: null, kind: 'end', primitive: 'choice', stakes: 'high', tree: true,
  question: 'In the Ender Dragon fight, what is the most useful action now?',
  trigger: 'Each step of the dragon fight in the End.',
  source: 'src/end-combat.js (fightEndStep)',
  options: [
    { pattern: 'crystal_\\d+', label: 'shoot this healing crystal', when: 'in view with a solved arrow path and not missed repeatedly', level: 'root', dynamic: true },
    { key: 'shoot_dragon', label: 'shoot the flying dragon', when: 'a bow, arrows and a clear trajectory', level: 'root' },
    { key: 'bed_bomb', label: 'blow a bed beside the perched dragon\'s head', when: 'the dragon perched, a bed carried, health fourteen or more, and a trench line within twelve blocks', level: 'root' },
    { key: 'strike_head', label: 'strike the perched dragon\'s head', when: 'the head is within sword reach', level: 'root' },
    { pattern: 'move_[a-z0-9_,.:-]+', label: 'move along this checked route', when: 'a safe surveyed route toward a crystal, the dragon or away from danger', level: 'root', dynamic: true },
    { key: 'observe', label: 'wait one second and watch', when: 'on a safe spot with the dragon in view, fewer than five idle watches in a row', level: 'root' },
  ],
  instructions: endDecisionInstructions,
  ungated: 'Jev\'s pick is taken at any confidence and asked again each step; Jev not reachable, the bot holds and it is asked again (jev-down.js)',
});

module.exports = {};
